# Generated by Django 5.0.4 on 2024-04-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliernetwork',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
